# Generated by Django 4.0.8 on 2022-10-28 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de operacion',
                'verbose_name_plural': 'Tipos de operaciones',
                'db_table': 'tipo_operacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SistemLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_usuario', models.CharField(max_length=20)),
                ('log_nombre', models.CharField(max_length=20)),
                ('log_apellido', models.CharField(max_length=20)),
                ('log_documento', models.IntegerField()),
                ('log_fecha_operacion', models.DateTimeField()),
                ('log_operacion_detalle', models.CharField(max_length=100)),
                ('log_tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recibo.tipooperacion')),
            ],
            options={
                'verbose_name': 'Log de sistema',
                'verbose_name_plural': 'Logs de sistema',
                'db_table': 'sistem_logs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DatosAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('documento', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('fecha_ultimo_ingreso', models.DateTimeField()),
                ('fecha_ultima_modificacion', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos adicionales',
                'verbose_name_plural': 'Datos adicionales',
                'db_table': 'datos_adicionales',
                'ordering': ['id'],
            },
        ),
    ]
