# Generated by Django 4.0.8 on 2022-11-03 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recibo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosadicionales',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datosadicionales',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datosadicionales',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='datosadicionales',
            name='fecha_ultimo_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datosadicionales',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
