# Generated by Django 4.0.8 on 2022-11-03 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recibo', '0002_datosadicionales_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosadicionales',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
