# Generated by Django 4.0.8 on 2022-11-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo', '0005_alter_datosadicionales_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosadicionales',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
