# Generated by Django 4.0.8 on 2022-11-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo', '0006_alter_datosadicionales_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemlogs',
            name='log_fecha_operacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
