# Generated by Django 4.0.8 on 2022-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo', '0007_alter_sistemlogs_log_fecha_operacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='difusion/')),
            ],
        ),
    ]
