# Generated by Django 4.0.8 on 2022-11-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recibo', '0008_difusion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difusion',
            options={'ordering': ['id'], 'verbose_name': 'Difusion', 'verbose_name_plural': 'Difusiones'},
        ),
        migrations.AlterModelTable(
            name='difusion',
            table='difusiones',
        ),
    ]
