# Generated by Django 4.0.8 on 2022-11-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo', '0009_alter_difusion_options_alter_difusion_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='difusion',
            name='descripcion',
            field=models.CharField(default='algo', max_length=50),
            preserve_default=False,
        ),
    ]
