# Generated by Django 4.0.8 on 2022-12-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo', '0011_alter_sistemlogs_log_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosadicionales',
            name='apellido',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='datosadicionales',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
