# Generated by Django 4.0.8 on 2022-12-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo', '0012_alter_datosadicionales_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemlogs',
            name='log_apellido',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sistemlogs',
            name='log_nombre',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sistemlogs',
            name='log_usuario',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
